### ISSUE TITLE
Fallback to local storage

### ISSUE THREAD

**Issue by hj-collab** [sagikazarmark/caddy-fs-s3#120]
Hi,

Can the module be updated to look for SSL files on local disk before checking S3. If the file exists locally, then s3 request is not needed. This significantly improves TTFB even if the certificates aren’t loaded in memory. Some body implemented something similar here. https://github.com/thekonqueror/certmagic-s3

Best regards,

**Comment by sagikazarmark** [comment]
I'm not entirely sure I understand what you mean.

What SSL files?

**Comment by sagikazarmark** [comment]
I'm not sure that this module would work that way...

It implements Caddy's FS interface, so anything you suggest would have to be implemented in Caddy itself, not in this module.

**Comment by jpds** [comment]
The correct place for this question was https://github.com/techknowlogick/certmagic-s3/issues/6 as it relates to the storage of Caddy's TLS certificates (storing them on S3 for a Caddy cluster but then falling back on local disk as required).
