### ISSUE TITLE
bug: fails with a remote S3 host

### ISSUE THREAD

**Issue by tetra12** [sagikazarmark/caddy-fs-s3#196]
OS: Ubuntu 22.04.3
Minio:  docker RELEASE.2023-09-20T22-49-55Z

**Description**: I wanna serve a static file from a minio bucket called `buck-website`. I use Caddy with your plugin to serve a static `index.html` on both local host and remote host. I place the same `index.html` file in the root of `buck-website` bucket on both local and remote host.

**Issue**: Localhost works fine, remote host returns `404 - not found`:
```sh
# Local works
curl  localhost:7000
Hello world!

# Remote - 404
curl localhost:7001 - returns 404
```
Caddy logs:
```sh
2023/10/07 13:09:25.942 DEBUG   http.handlers.file_server       sanitized path join     {"site_root": ".", "request_path": "/", "result": "."}
2023/10/07 13:09:32.110 DEBUG   http.handlers.file_server       no index file in directory      {"path": ".", "index_filenames": ["index.html", "index.txt"]}
2023/10/07 13:09:32.110 DEBUG   http.log.error  {id=wwhe1qrpa} fileserver.(*FileServer).notFound (staticfiles.go:629): HTTP 404 {"request": {"remote_ip": "127.0.0.1", "remote_port": "42206", "client_ip": "127.0.0.1", "proto": "HTTP/1.1", "method": "GET", "host": "localhost:7001", "uri": "/", "headers": {"User-Agent": ["curl/7.81.0"], "Accept": ["*/*"]}}, "duration": 6.167626911, "status": 404, "err_id": "wwhe1qrpa", "err_trace": "fileserver.(*FileServer).notFound (staticfiles.go:629)"}
```

**Config**:
1. Minio host: s3

index.html: `hello world!`

2. Check S3 port: 
```sh
nc -zv s3 9000
Connection to s3 (xxx.xxx.xxx.xxx) 9000 port [tcp/*] succeeded!
```

3. `Caddyfile`:
```sh
:7000 {
	file_server {
		fs s3 {
			endpoint "http://localhost:9000"
			region "reg-0"
			bucket "buck-website"
			force_path_style
		}
	}
}

:7001 {
	file_server {
		fs s3 {
			endpoint "http://s3:9000"
			region "reg-0"
			bucket "buck-website"
			force_path_style
		}
	}
}

```

**Comment by sagikazarmark** [comment]
Do you run both MinIO and Caddy in Docker?

**Comment by tetra12** [comment]
> Do you run both MinIO and Caddy in Docker?

I run minio in docker on both local and remote. Caddy is built from the latest source, including your plugin

**Comment by tetra12** [comment]
Upd: If I add a `pass_thru` directive, caddy returns 200, but fails to find `index.html`. NGINX is able to serve the static website in that bucket

```sh
:7001 {
	file_server {
		fs s3 {
			endpoint "http://s3:9000"
			region "us-east-0"
			bucket "buck-website"
			force_path_style
		}
		pass_thru
	}
}
```

```sh
2023/10/07 20:09:34.923 INFO    serving initial configuration
2023/10/07 20:09:37.333 DEBUG   http.handlers.file_server       sanitized path join     {"site_root": ".", "request_path": "/", "result": "."}
2023/10/07 20:09:37.421 DEBUG   http.handlers.file_server       no index file in directory      {"path": ".", "index_filenames": ["index.html", "index.txt"]}
```

**Comment by sagikazarmark** [comment]
@tetra12 I'm not 100% sure what "remote" means in this case.

`http://s3:9000` suggests you are trying to access a MinIO instance running in a container using DNS, but if Caddy doesn't run in a container, in the same network, etc. that's not going to work.

Can you create a reproducible environment to demonstrate the problem?

(Side note: I suspect at this point that the problem is not related to this library as it's merely a wrapper around AWS lib and `io/fs`)

**Comment by tetra12** [comment]
I mean what I say. I personally use a fresh VPS instance, running minio docker and having a static IP. You can reproduce the issue with your own cloud or VPS instance. I provided enough info to reproduce

**Comment by tetra12** [comment]
This issue is invalid. My bad. I had an issue with valid S3 credentials. Closing as invalid
