### ISSUE TITLE
How does it sync up the new files that are updated in S3

### ISSUE THREAD

**Issue by amitchavan90** [sagikazarmark/caddy-fs-s3#386]
How this plugin will fetch newly added/updated files from S3? or it'll not sync the files but forward each request to S3 to fetch the file irrespective of whether it is new/updated/old?

Thanks in advance

**Comment by sagikazarmark** [comment]
I'm not entirely sure that this is what you are asking, but no, it doesn't store or cache files. It acts as a simple proxy to S3.

**Comment by amitchavan90** [comment]
ok thank you.
