### ISSUE TITLE
Clarify what 'path style' even means

### ISSUE THREAD

**Issue by adworacz** [sagikazarmark/caddy-fs-s3#460]
The [docs](https://caddyserver.com/docs/modules/caddy.fs.s3) for `use_path_style` state:

>  Set this to true to enable the client to use path-style addressing.

But it's never explained what "path-style" addressing even means. It's not clear to me if I should enable this option or not.

I think both a more detailed explanation and perhaps some examples would help immensely here.

**Comment by sagikazarmark** [comment]
Path-style addressing is an S3 feature, there is nothing specific about it in this library: https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html#path-style-access

**Comment by adworacz** [comment]
Thank you for the clarification, this was not something I was aware of existed, and I've worked with AWS for years (ref: I've been an Amazon employee for 13+ years).

Based on that link, it appears the feature is intended to be deprecated and removed:

> However, path-style URLs will be discontinued in the future.

I'd simply suggest adding a link to the document you posted as part of this project's documentation, with perhaps a warning stating that S3 intendeds to remove it in the future.

Thank you for your hard work on this project.
