### ISSUE TITLE
cant get it to work with s3

### ISSUE THREAD

**Issue by manuelfrans** [sagikazarmark/caddy-fs-s3#6]
Hello . i discovered this module and installed it via xcaddy
My architecture is to have muliple servers (EC2 instances) running its own versions of caddy
I'm hoping this plugin gives it a shared storage

somehow i cant get it to work. can you help me ?
AM i missing something. I'm a newbie to caddy so any help would do 

https:// {

        tls {
        on_demand
    }

       root * /var/www
        encode zstd gzip
       file_server {
	fs s3 {
		bucket "caddy2"
		region "eu-west-3"
	      endpoint "https://caddy2.s3.eu-west-3.amazonaws.com"
		# profile <profile>
		# force_path_style
	}
}
        php_fastcgi unix//var/run/php/php8.1-fpm.sock
}

**Comment by sagikazarmark** [comment]
First of all, the endpoint is optional and for AWS S3 you don't have to set that.

Secondly: please format your Caddyfile and put them in markdown codeblocks, like this:

````markdown
```
https:// {
...
```
````

Third: can you please clarify what's going wrong exactly? Do you get an error?

Last, but not least: if you have a routing problem (ie. your files are unavailable) try using a local filesystem first. If it works that way, then there is probably something going on with this plugin.

If it doesn't work with local files either, you can ask help on the forum: https://caddy.community/ (I'm not a huge Caddy magician either).

My gut tells me that this isn't a problem with this plugin, so I'd try the above.

**Comment by manuelfrans** [comment]
```
https:// {

    tls {
    on_demand
}


   root * /var/www
    encode zstd gzip
   file_server {
fs s3 {
	bucket "caddy2"
	region "eu-west-3"
      endpoint "https://caddy2.s3.eu-west-3.amazonaws.com"
	# profile <profile>
	# force_path_style
}
}
php_fastcgi unix//var/run/php/php8.1-fpm.sock
}
```

WHen I add the fs s3 block, i get 404 in my browser 
When i remove it it works

I created a bucket just for this and i dont see it create any certificates
the only credentials i filled out were  these

bucket "caddy2"
	region "eu-west-3"
      endpoint "https://caddy2.s3.eu-west-3.amazonaws.com"

DId i need to fill in more environment variables or something ??
or perhaps have some settings in AWS ??

**Comment by sagikazarmark** [comment]
I guess you figured it out then?
