### ISSUE TITLE
Auth support?

### ISSUE THREAD

**Issue by jimafisk** [sagikazarmark/caddy-fs-s3#7]
I'd like to [Proxy DigitalOcean Spaces (S3 clone) with authorization](https://caddy.community/t/proxy-digitalocean-spaces-s3-clone-with-authorization/2768).

Does this module allow me to use access keys to retrieve private files? Thank you!

**Comment by sagikazarmark** [comment]
Storing access keys in Caddyfile itself is probably not a great idea. You can use the features of the underlying AWS SDK though. If you set any of the standard environment variables for AWS SDK/CLI, it should work.

You can also use multiple profiles and set the profile in your Caddyfile.

Hope that helps.

**Comment by jimafisk** [comment]
Thanks for the quick reply! So theoretically I could set [env variables](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html) like:

```
AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
```

Then I would be able to use that like:

```
example.com

file_server {
	fs s3 {
		bucket mybucket
		region nyc3.digitaloceanspaces.com

		'credentials' => [
                      'key'    => {AWS_ACCESS_KEY_ID},
                      'secret' => {AWS_SECRET_ACCESS_KEY},
                ],
	}
}
```

Not sure exactly how to format the syntax for that kind of request. Thank you!

**Comment by sagikazarmark** [comment]
You don't need the credentials block. Setting the env cars should be enough.

**Comment by jimafisk** [comment]
Oh perfect! I guess I'd only need that if I wanted to use a different env variable name?

```
example.com

file_server {
	fs s3 {
		bucket mybucket
		region nyc3.digitaloceanspaces.com
                accessKeyId {DO_ACCESS_KEY}
                secretAccessKey {DO_SECRET_KEY}
	}
}
```

Is there a reference I could look at for getting the keys / syntax correct? Thanks!

**Comment by sagikazarmark** [comment]
This is all you need:

```
example.com

file_server {
	fs s3 {
		bucket mybucket
		endpoint nyc3.digitaloceanspaces.com
		force_path_style
	}
}
```

```shell
export AWS_ACCESS_KEY_ID=...
export AWS_SECRET_ACCESS_KEY=...

caddy
```

Here is the reference: https://github.com/sagikazarmark/caddy-fs-s3#usage

**Comment by ziggycross** [comment]
Is this fixed? I'm trying this currently and getting an error. I've set up my key environment variables according to your last message, but still can't retrieve my file to do "no EC2 IMDS role found". This is from a public bucket, stored on Supabase, and if I go directly to the file's URL there is no problem.

```
server@localhost ~ % ./caddy version
v2.8.4 h1:q3pe0wpBj1OcHFZ3n/1nl4V4bxBrYoSoab7rL9BMYNk=
```

When I try to access the resource I get this error:
```
2024/11/18 04:01:19.670	ERROR	http.log.error	open test-uid-001/index.html: operation error S3: GetObject, get identity: get credentials: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, http response error StatusCode: 404, request to EC2 IMDS failed	{"request": {"remote_ip": "<MY IP ADDRESS>", "remote_port": "61630", "client_ip": "<MY IP ADDRESS>", "proto": "HTTP/1.1", "method": "GET", "host": "<SERVER IP ADDRESS>", "uri": "/test-uid-001/index.html", "headers": {"Accept-Encoding": ["gzip, deflate"], "Connection": ["keep-alive"], "Upgrade-Insecure-Requests": ["1"], "Accept": ["text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"], "User-Agent": ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15"], "Accept-Language": ["en-AU,en;q=0.9"]}}, "duration": 0.001138951, "status": 500, "err_id": "629qiubiv", "err_trace": "fileserver.(*FileServer).ServeHTTP (staticfiles.go:285)"}
```

Are there other ways of doing this I should be trying?

**Comment by sagikazarmark** [comment]
Honestly, I haven't tried this with public buckets. I'm not quite sure if accessing the bucket through the S3 API is supposed to work without authentication.

AFAIK a bucket's "public" nature is just an additional HTTP interface to access the objects, and going through the API (which is what this plugin does) may still require authentication...but I could be wrong there.

I wonder, though: if it's a public bucket, why do you need this plugin? I mean, if you wanted to hide the bucket behind a custom URL, you could just use the reverse proxy component of Caddy, couldn't you?

**Comment by nikooo777** [comment]
hey, sorry for digging this up, however it would be nice if this information was provided in the readme. I spent quite some time reading through the source code and eventually looking all the open and closed issues before figuring out how to set keys/secrets.

I appreciate the module, however I was so close to just writing my own as this was my 3rd module I'd been trying with almost no documentation on how to use it.

**Comment by sagikazarmark** [comment]
Added a section about authentication in the documentation: https://github.com/sagikazarmark/caddy-fs-s3?tab=readme-ov-file#authentication
